# Generated by Django 4.2.2 on 2023-06-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_rename_literarygenre_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublishingHouse',
            new_name='Publication',
        ),
    ]
