# Generated by Django 4.2.2 on 2023-07-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_rename_publishinghouse_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_house',
            new_name='publication',
        ),
    ]
