# Generated by Django 4.2.2 on 2023-07-07 08:33

from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "fixture_data.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("shelves", "0004_rename_pub_house_book_publication"),
    ]

    operations = [
        migrations.RunPython(func, reverse_func),
    ]
